spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:file:./data/demo}
    username: ${JDBC_DATABASE_USERNAME:sql7587247}
    password: ${JDBC_DATABASE_PASSWORD:Z3jEdH8UiK}
    driverClassName: org.h2.Driver
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mail:
    host: 0.0.0.0
    port: 1025

springdoc:
  pathsToMatch: /api/**

application:
  security:
    access-token-secret: adadawdawdaadawrarhfthfthfhfhffthffth
    refresh-token-secret: awdawrawrawradwdafthfhfthfthfthfhfth
    forgot-token-secret: awrarwafafarfwafrawrfhfthfhfhfhffhfh
  frontend:
    default-url: http://localhost:8081